### PR TITLE
Add hide/show method to manipulators.

### LINKED ISSUE #6: Show, hide and remove items
I'm missing methods or properties for hiding, showing and removing items/item groups or parts like options of a select. I like to do this to react to hardware platforms (e.g. remove dropdown items related to health for Aplite) or hide and show options related to certain selections (e.g. hide date related options if none of the slots in a watchface is configured to show a date)

### PR DESCRIPTION
**Pull request by keegan-lillo**
resolves #6

### CODE REVIEW

**Comment by matthewtole** [comment]
Can you show / hide a whole section using this?

**Comment by keegan-lillo** [comment]
No. It only works for individual items. Sections don't actually have manipulators. You would need to hide all the items in a section and there is no way to get a reference to a section in the API either. And I just noticed that bad things happen to the separators if the hidden item is last in the list.

**Comment by keegan-lillo** [comment]
okay I fixed the CSS to consider empty sections and also fixed the separators showing up when they shouldn't. There is still no way to hide an entire section. You have to hide all items in a section. In the future we could add ways of selecting all items in a section to make this easier.

**Comment by matthewtole** [comment]
Is there somewhere you can document these new methods, along with the solution for hiding a whole section?

**Comment by matthewtole** [comment]
Once documented, :+1:

**Pull request merged**
