### PR TITLE
Separate the results of the checkboxgroup manipulator with a zero.

### LINKED ISSUE #13: Javacript conversion mandatory for checkboxgroups
The getValue of a `checkboxgroup` returns an array of strings 
``` json
{"enableBackground":1,"background":65280,"font_size":"2","test":["sushi","burgers"]}
```
If we let Clay handle 'showConfiguration' and 'webviewclosed' events, an array of bytes is sent to the watchapp for the `test` key containing : 
`['s','u','s','h','i','b','u','r','g','e','r','s']`

So without javascript convertion, it is really not easy to use this in the C code.
Clay should also return \0 character like that : 
``` json
{"enableBackground":1,"background":65280,"font_size":"2","test":["sushi",0,"burgers",0]}
```
so the string delimiter will permit to split the result in C.

### PR DESCRIPTION
**Pull request by keegan-lillo**
Fixes #13

### CODE REVIEW

**Comment by keegan-lillo** [comment]
@gregoiresage Does this work for you?

**Comment by gregoiresage** [comment]
I will try when I'll go back from holidays Saturday.
Thanks for the evolution!
Le 29 févr. 2016 3:16 AM, "keegan-lillo" <notifications@github.com> a
écrit :

**Comment by keegan-lillo** [comment]
Actually I wonder if maybe a `\0` character might be a better separator. Colors are represented as numbers and black happens to be `0`

**Comment by keegan-lillo** [comment]
@matthewtole what are your thoughts on the separator to use. I'd like to recycle this format for something like this: #4 in the future hence my concern over color values

**Comment by matthewtole** [comment]
I think that you're putting the solution to the problem in the wrong place. Instead of muddling up the results of the `get()` method, it would be better if the function that handles serialising the form to send to the watch handles this. That way it becomes a general solution that can be used by any component,

**Comment by keegan-lillo** [comment]
So in here https://github.com/pebble/clay/blob/master/src/scripts/lib/clay-config.js#L161 do something like 
```javascript
switch(typeof _settings[appKey]) {
  case 'array': 
    _settings[appKey] = Utils.addSeparators(item.get(), 0);
    break;
  default: 
    _settings[appKey] = item.get();
    break;
}



```

**Comment by keegan-lillo** [comment]
@matthewtole after discussing with @gregoiresage we have found that only string arrays needed to be split up with zeros. Number arrays will be sent as is. This will pave the way for future changes where we might want to send different types of arrays. Also arrays that have booleans in them will now be converted to ones and zeros.

**Comment by matthewtole** [comment]
Sounds good to me. :+1:

**Pull request merged**
